version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PA55w0rd2024"
    ports:
      - "1433:1433"
    networks:
      - backend
  api: 
    image: api:dev
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - DBServer=sqlserver
      - DBPort=1433
      - DBUser=SA
      - DBPassword=PA55w0rd2024
      - Database=Fiap
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend  
    depends_on:
      - sqlserver

networks:
  backend:
    driver: bridge