name: Build and Deploy Store and Payment to Azure AKS

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' 

    - name: Clean Store API
      run: |
        dotnet clean ./store/src/API/API.csproj
        dotnet clean ./store/src/Application/Application.csproj
        dotnet clean ./store/src/Domain/Domain.csproj
        dotnet clean ./store/src/Infra/Infra.csproj
        
    # Restore and Build Store API
    - name: Restore dependencies for Store API
      run: |
        dotnet restore ./store/src/API/API.csproj
        dotnet restore ./store/src/Application/Application.csproj
        dotnet restore ./store/src/Domain/Domain.csproj
        dotnet restore ./store/src/Infra/Infra.csproj

    - name: Build Store API
      run: |
        dotnet build ./store/src/API/API.csproj --configuration Release --no-restore
        dotnet build ./store/src/Application/Application.csproj --configuration Release --no-restore
        dotnet build ./store/src/Domain/Domain.csproj --configuration Release --no-restore
        dotnet build ./store/src/Infra/Infra.csproj --configuration Release --no-restore


    - name: Clean Payment API
      run: dotnet clean ./payment/src/API/PaymentWebhook.csproj

    # Restore and Build Payment API
    - name: Restore dependencies for Payment API
      run: dotnet restore ./payment/src/API/PaymentWebhook.csproj

    - name: Build Payment API
      run: dotnet build ./payment/src/API/PaymentWebhook.csproj --configuration Release --no-restore

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry (ACR)
      run: |
        echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login ${{ env.ACR_NAME }}.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

    - name: Build and Push Docker image for Store
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/store:dev ./store
        docker push ${{ env.ACR_NAME }}.azurecr.io/store:dev

    - name: Build and Push Docker image for Payment
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/payment:dev ./payment
        docker push ${{ env.ACR_NAME }}.azurecr.io/payment:dev

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

    - name: Deploy Store image to AKS
      run: |
        kubectl set image deployment/store-api store-api=${{ env.ACR_NAME }}.azurecr.io/store:dev
        kubectl rollout status deployment/store-api

    - name: Deploy Payment image to AKS
      run: |
        kubectl set image deployment/payment-api payment-api=${{ env.ACR_NAME }}.azurecr.io/payment:dev
        kubectl rollout status deployment/payment-api
